import { describe, it, expect } from 'vitest';
import { injectSection } from '../../src/output/claudemd-injector.js';

const SECTION = [
  '<!-- CARTOGRAPH:START — Generated by `cartograph generate`. Do not edit manually. -->',
  '## Codebase Navigation (Cartograph)',
  '',
  'Tool guidance here.',
  '<!-- CARTOGRAPH:END -->',
].join('\n');

describe('injectSection', () => {
  it('appends section to file without markers', () => {
    const existing = '# My Project\n\nSome content.\n';
    const result = injectSection(existing, SECTION);
    expect(result).toContain('# My Project');
    expect(result).toContain('Some content.');
    expect(result).toContain('CARTOGRAPH:START');
    expect(result).toContain('Tool guidance here.');
    expect(result).toContain('CARTOGRAPH:END');
    // Original content comes first
    expect(result.indexOf('My Project')).toBeLessThan(result.indexOf('CARTOGRAPH:START'));
  });

  it('replaces existing section between markers', () => {
    const existing = [
      '# My Project\n',
      '<!-- CARTOGRAPH:START — Generated by `cartograph generate`. Do not edit manually. -->',
      '## Old section',
      'Old content.',
      '<!-- CARTOGRAPH:END -->',
      '\n## Other Stuff\n',
      'More content.',
    ].join('\n');
    const result = injectSection(existing, SECTION);
    // Old content replaced
    expect(result).not.toContain('Old content.');
    expect(result).not.toContain('Old section');
    // New content present
    expect(result).toContain('Tool guidance here.');
    // Surrounding content preserved
    expect(result).toContain('# My Project');
    expect(result).toContain('## Other Stuff');
    expect(result).toContain('More content.');
  });

  it('handles markers at the end of file', () => {
    const existing = [
      '# My Project\n',
      '<!-- CARTOGRAPH:START — Generated by `cartograph generate`. Do not edit manually. -->',
      'Old stuff.',
      '<!-- CARTOGRAPH:END -->',
    ].join('\n');
    const result = injectSection(existing, SECTION);
    expect(result).toContain('Tool guidance here.');
    expect(result).not.toContain('Old stuff.');
    expect(result).toContain('# My Project');
  });

  it('handles empty file', () => {
    const result = injectSection('', SECTION);
    expect(result).toContain('CARTOGRAPH:START');
    expect(result).toContain('Tool guidance here.');
  });

  it('preserves trailing newline', () => {
    const existing = '# My Project\n';
    const result = injectSection(existing, SECTION);
    expect(result).toMatch(/\n$/);
  });

  it('only has one pair of markers after injection', () => {
    const existing = '# My Project\n';
    const result = injectSection(existing, SECTION);
    const startCount = (result.match(/CARTOGRAPH:START/g) || []).length;
    const endCount = (result.match(/CARTOGRAPH:END/g) || []).length;
    expect(startCount).toBe(1);
    expect(endCount).toBe(1);
  });
});
