import type pg from 'pg';
import { resolve } from 'path';
import { mkdirSync, writeFileSync } from 'fs';
import { RepoRepository } from '../db/repositories/repo-repository.js';
import { GenerateError } from '../errors.js';
import { generateRoot } from './root-generator.js';

const HEADER = '<!-- Generated by Cartograph. Do not edit manually. -->\n\n';

export interface GenerateOptions {
  outputDir?: string;
}

export interface DirectoryStats {
  path: string;
  fileCount: number;
  symbolCount: number;
  classCount: number;
  dominantKinds: string[];
}

export interface RepoStats {
  totalFiles: number;
  totalSymbols: number;
  totalReferences: number;
  language: string;
  directories: DirectoryStats[];
}

export class GeneratePipeline {
  private repoRepo: RepoRepository;

  constructor(private pool: pg.Pool) {
    this.repoRepo = new RepoRepository(pool);
  }

  async run(repoPath: string, opts: GenerateOptions = {}): Promise<void> {
    const absPath = resolve(repoPath);
    const outputDir = opts.outputDir || `${absPath}/.cartograph`;

    // 1. Find the repo in the DB
    const repo = await this.repoRepo.findByPath(absPath);
    if (!repo) {
      throw new GenerateError(
        `Repository not indexed: ${absPath}. Run \`cartograph index <path>\` first.`
      );
    }

    // 2. Check for empty index
    const { rows: fileCount } = await this.pool.query(
      'SELECT COUNT(*)::int AS count FROM files WHERE repo_id = $1',
      [repo.id]
    );
    if ((fileCount[0].count as number) === 0) {
      throw new GenerateError(
        `No indexed data found for ${absPath}. Run \`cartograph index <path>\` first.`
      );
    }

    // 3. Query data and generate files
    mkdirSync(outputDir, { recursive: true });

    const repoStats = await this.queryRepoStats(repo.id);
    writeFileSync(`${outputDir}/CLAUDE.md`, HEADER + generateRoot(repoStats));

    // Placeholders for remaining generators
    writeFileSync(`${outputDir}/modules.md`, HEADER + '# Modules\n\n_Coming soon_\n');
    writeFileSync(`${outputDir}/dependencies.md`, HEADER + '# Dependencies\n\n_Coming soon_\n');
    writeFileSync(`${outputDir}/conventions.md`, HEADER + '# Conventions\n\n_Coming soon_\n');

    // 4. Print summary
    console.log('\n✅ Generated .cartograph/CLAUDE.md + 3 topic files');
    console.log('   Add this to your root CLAUDE.md:');
    console.log('   Also read: .cartograph/CLAUDE.md\n');
  }

  private async queryRepoStats(repoId: number): Promise<RepoStats> {
    const { rows: fileCounts } = await this.pool.query(
      'SELECT COUNT(*)::int AS count, MAX(language) AS language FROM files WHERE repo_id = $1',
      [repoId]
    );

    const { rows: symbolCounts } = await this.pool.query(
      `SELECT COUNT(*)::int AS count FROM symbols s
       JOIN files f ON s.file_id = f.id WHERE f.repo_id = $1`,
      [repoId]
    );

    const { rows: refCounts } = await this.pool.query(
      `SELECT COUNT(*)::int AS count FROM symbol_references sr
       JOIN symbols s ON sr.source_symbol_id = s.id
       JOIN files f ON s.file_id = f.id WHERE f.repo_id = $1`,
      [repoId]
    );

    const { rows: dirRows } = await this.pool.query(
      `SELECT
         split_part(f.path, '/', 1) ||
           CASE WHEN position('/' in f.path) > 0
                THEN '/' || split_part(f.path, '/', 2)
                ELSE '' END AS dir,
         COUNT(DISTINCT f.id)::int AS file_count,
         COUNT(s.id)::int AS symbol_count,
         COUNT(s.id) FILTER (WHERE s.kind = 'class')::int AS class_count,
         array_agg(DISTINCT s.kind) FILTER (WHERE s.kind IN ('class','interface','trait','enum')) AS dominant_kinds
       FROM files f
       LEFT JOIN symbols s ON s.file_id = f.id
       WHERE f.repo_id = $1
       GROUP BY dir
       ORDER BY symbol_count DESC`,
      [repoId]
    );

    return {
      totalFiles: fileCounts[0].count as number,
      totalSymbols: symbolCounts[0].count as number,
      totalReferences: refCounts[0].count as number,
      language: (fileCounts[0].language as string) || 'unknown',
      directories: dirRows.map(r => ({
        path: r.dir as string,
        fileCount: r.file_count as number,
        symbolCount: r.symbol_count as number,
        classCount: r.class_count as number,
        dominantKinds: (r.dominant_kinds as string[]) || [],
      })),
    };
  }
}
