import type pg from 'pg';
import { resolve } from 'path';
import { mkdirSync, writeFileSync } from 'fs';
import { RepoRepository } from '../db/repositories/repo-repository.js';
import { GenerateError } from '../errors.js';
import { generateRoot } from './root-generator.js';
import { generateModules } from './modules-generator.js';
import { generateDeps } from './deps-generator.js';
import { generateConventions } from './conventions-generator.js';

const HEADER = '<!-- Generated by Cartograph. Do not edit manually. -->\n\n';

export interface GenerateOptions {
  outputDir?: string;
}

export interface DirectoryStats {
  path: string;
  fileCount: number;
  symbolCount: number;
  classCount: number;
  dominantKinds: string[];
}

export interface RepoStats {
  totalFiles: number;
  totalSymbols: number;
  totalReferences: number;
  language: string;
  directories: DirectoryStats[];
}

export interface ModuleSymbol {
  qualifiedName: string;
  kind: string;
  linesOfCode: number;
  implements: string[];
  extends: string | null;
  traits: string[];
  referenceCount: number;
}

export interface ModuleInfo {
  path: string;
  symbols: ModuleSymbol[];
}

export interface ModuleDependency {
  sourceModule: string;
  targetModule: string;
  referenceCount: number;
}

export interface ExternalDependency {
  namespace: string;
  referenceCount: number;
}

export interface DepsData {
  internal: ModuleDependency[];
  external: ExternalDependency[];
}

export interface ConventionsData {
  totalClasses: number;
  totalInterfaces: number;
  totalTraits: number;
  totalEnums: number;
  classesWithInterface: number;
  classesWithInheritance: number;
  classesWithTraits: number;
  interfaceAdoptionByModule: Map<string, { total: number; withInterface: number }>;
  classNames: string[];
  methodNames: string[];
}

export class GeneratePipeline {
  private repoRepo: RepoRepository;

  constructor(private pool: pg.Pool) {
    this.repoRepo = new RepoRepository(pool);
  }

  async run(repoPath: string, opts: GenerateOptions = {}): Promise<void> {
    const absPath = resolve(repoPath);
    const outputDir = opts.outputDir || `${absPath}/.cartograph`;

    // 1. Find the repo in the DB
    const repo = await this.repoRepo.findByPath(absPath);
    if (!repo) {
      throw new GenerateError(
        `Repository not indexed: ${absPath}. Run \`cartograph index <path>\` first.`
      );
    }

    // 2. Check for empty index
    const { rows: fileCount } = await this.pool.query(
      'SELECT COUNT(*)::int AS count FROM files WHERE repo_id = $1',
      [repo.id]
    );
    if ((fileCount[0].count as number) === 0) {
      throw new GenerateError(
        `No indexed data found for ${absPath}. Run \`cartograph index <path>\` first.`
      );
    }

    // 3. Query data and generate files
    mkdirSync(outputDir, { recursive: true });

    const repoStats = await this.queryRepoStats(repo.id);
    writeFileSync(`${outputDir}/CLAUDE.md`, HEADER + generateRoot(repoStats));

    const modules = await this.queryModules(repo.id);
    writeFileSync(`${outputDir}/modules.md`, HEADER + generateModules(modules));

    const deps = await this.queryDependencies(repo.id);
    writeFileSync(`${outputDir}/dependencies.md`, HEADER + generateDeps(deps));
    const conventions = await this.queryConventions(repo.id);
    writeFileSync(`${outputDir}/conventions.md`, HEADER + generateConventions(conventions));

    // 4. Print summary
    console.log('\n✅ Generated .cartograph/CLAUDE.md + 3 topic files');
    console.log('   Add this to your root CLAUDE.md:');
    console.log('   Also read: .cartograph/CLAUDE.md\n');
  }

  private async queryRepoStats(repoId: number): Promise<RepoStats> {
    const { rows: fileCounts } = await this.pool.query(
      'SELECT COUNT(*)::int AS count, MAX(language) AS language FROM files WHERE repo_id = $1',
      [repoId]
    );

    const { rows: symbolCounts } = await this.pool.query(
      `SELECT COUNT(*)::int AS count FROM symbols s
       JOIN files f ON s.file_id = f.id WHERE f.repo_id = $1`,
      [repoId]
    );

    const { rows: refCounts } = await this.pool.query(
      `SELECT COUNT(*)::int AS count FROM symbol_references sr
       JOIN symbols s ON sr.source_symbol_id = s.id
       JOIN files f ON s.file_id = f.id WHERE f.repo_id = $1`,
      [repoId]
    );

    const { rows: dirRows } = await this.pool.query(
      `SELECT
         split_part(f.path, '/', 1) ||
           CASE WHEN position('/' in f.path) > 0
                THEN '/' || split_part(f.path, '/', 2)
                ELSE '' END AS dir,
         COUNT(DISTINCT f.id)::int AS file_count,
         COUNT(s.id)::int AS symbol_count,
         COUNT(s.id) FILTER (WHERE s.kind = 'class')::int AS class_count,
         array_agg(DISTINCT s.kind) FILTER (WHERE s.kind IN ('class','interface','trait','enum')) AS dominant_kinds
       FROM files f
       LEFT JOIN symbols s ON s.file_id = f.id
       WHERE f.repo_id = $1
       GROUP BY dir
       ORDER BY symbol_count DESC`,
      [repoId]
    );

    return {
      totalFiles: fileCounts[0].count as number,
      totalSymbols: symbolCounts[0].count as number,
      totalReferences: refCounts[0].count as number,
      language: (fileCounts[0].language as string) || 'unknown',
      directories: dirRows.map(r => ({
        path: r.dir as string,
        fileCount: r.file_count as number,
        symbolCount: r.symbol_count as number,
        classCount: r.class_count as number,
        dominantKinds: (r.dominant_kinds as string[]) || [],
      })),
    };
  }

  private async queryModules(repoId: number): Promise<ModuleInfo[]> {
    const { rows } = await this.pool.query(
      `SELECT
         s.qualified_name,
         s.kind,
         f.path AS file_path,
         (s.line_end - s.line_start + 1) AS lines_of_code,
         split_part(f.path, '/', 1) ||
           CASE WHEN position('/' in f.path) > 0
                THEN '/' || split_part(f.path, '/', 2)
                ELSE '' END AS module_dir,
         (SELECT COUNT(*)::int FROM symbol_references WHERE target_symbol_id = s.id) AS ref_count,
         COALESCE(
           (SELECT array_agg(sr.target_qualified_name)
            FROM symbol_references sr
            WHERE sr.source_symbol_id = s.id AND sr.reference_kind = 'implementation'),
           '{}'
         ) AS implements,
         (SELECT sr.target_qualified_name
          FROM symbol_references sr
          WHERE sr.source_symbol_id = s.id AND sr.reference_kind = 'inheritance'
          LIMIT 1) AS extends_from,
         COALESCE(
           (SELECT array_agg(sr.target_qualified_name)
            FROM symbol_references sr
            WHERE sr.source_symbol_id = s.id AND sr.reference_kind = 'trait_use'),
           '{}'
         ) AS uses_traits
       FROM symbols s
       JOIN files f ON s.file_id = f.id
       WHERE f.repo_id = $1
         AND s.kind IN ('class', 'interface', 'trait', 'enum')
         AND s.parent_symbol_id IS NULL
       ORDER BY module_dir, ref_count DESC`,
      [repoId]
    );

    const moduleMap = new Map<string, ModuleSymbol[]>();
    for (const row of rows) {
      const dir = row.module_dir as string;
      const list = moduleMap.get(dir) || [];
      list.push({
        qualifiedName: row.qualified_name as string,
        kind: row.kind as string,
        linesOfCode: row.lines_of_code as number,
        implements: (row.implements as string[]) || [],
        extends: (row.extends_from as string) || null,
        traits: (row.uses_traits as string[]) || [],
        referenceCount: row.ref_count as number,
      });
      moduleMap.set(dir, list);
    }

    return Array.from(moduleMap.entries())
      .map(([path, symbols]) => ({ path, symbols }))
      .sort((a, b) => {
        const aTotal = a.symbols.reduce((sum, s) => sum + s.referenceCount, 0);
        const bTotal = b.symbols.reduce((sum, s) => sum + s.referenceCount, 0);
        return bTotal - aTotal;
      });
  }

  private async queryDependencies(repoId: number): Promise<DepsData> {
    const { rows: internalRows } = await this.pool.query(
      `SELECT source_module, target_module, ref_count FROM (
         SELECT
           split_part(sf.path, '/', 1) ||
             CASE WHEN position('/' in sf.path) > 0
                  THEN '/' || split_part(sf.path, '/', 2)
                  ELSE '' END AS source_module,
           split_part(tf.path, '/', 1) ||
             CASE WHEN position('/' in tf.path) > 0
                  THEN '/' || split_part(tf.path, '/', 2)
                  ELSE '' END AS target_module,
           COUNT(*)::int AS ref_count
         FROM symbol_references sr
         JOIN symbols ss ON sr.source_symbol_id = ss.id
         JOIN files sf ON ss.file_id = sf.id
         JOIN symbols ts ON sr.target_symbol_id = ts.id
         JOIN files tf ON ts.file_id = tf.id
         WHERE sf.repo_id = $1 AND tf.repo_id = $1
           AND sr.target_symbol_id IS NOT NULL
         GROUP BY source_module, target_module
       ) sub
       WHERE source_module != target_module
       ORDER BY ref_count DESC`,
      [repoId]
    );

    const { rows: externalRows } = await this.pool.query(
      `SELECT
         split_part(sr.target_qualified_name, E'\\\\', 1) AS namespace,
         COUNT(*)::int AS ref_count
       FROM symbol_references sr
       JOIN symbols s ON sr.source_symbol_id = s.id
       JOIN files f ON s.file_id = f.id
       WHERE f.repo_id = $1
         AND sr.target_symbol_id IS NULL
       GROUP BY namespace
       ORDER BY ref_count DESC`,
      [repoId]
    );

    return {
      internal: internalRows.map(r => ({
        sourceModule: r.source_module as string,
        targetModule: r.target_module as string,
        referenceCount: r.ref_count as number,
      })),
      external: externalRows.map(r => ({
        namespace: r.namespace as string,
        referenceCount: r.ref_count as number,
      })),
    };
  }

  private async queryConventions(repoId: number): Promise<ConventionsData> {
    const { rows: kindCounts } = await this.pool.query(
      `SELECT s.kind, COUNT(*)::int AS count
       FROM symbols s JOIN files f ON s.file_id = f.id
       WHERE f.repo_id = $1 AND s.kind IN ('class','interface','trait','enum')
         AND s.parent_symbol_id IS NULL
       GROUP BY s.kind`,
      [repoId]
    );
    const countMap = Object.fromEntries(kindCounts.map(r => [r.kind, r.count]));

    const { rows: implCount } = await this.pool.query(
      `SELECT COUNT(DISTINCT sr.source_symbol_id)::int AS count
       FROM symbol_references sr
       JOIN symbols s ON sr.source_symbol_id = s.id
       JOIN files f ON s.file_id = f.id
       WHERE f.repo_id = $1 AND sr.reference_kind = 'implementation'`,
      [repoId]
    );

    const { rows: inheritCount } = await this.pool.query(
      `SELECT COUNT(DISTINCT sr.source_symbol_id)::int AS count
       FROM symbol_references sr
       JOIN symbols s ON sr.source_symbol_id = s.id
       JOIN files f ON s.file_id = f.id
       WHERE f.repo_id = $1 AND sr.reference_kind = 'inheritance'`,
      [repoId]
    );

    const { rows: traitCount } = await this.pool.query(
      `SELECT COUNT(DISTINCT sr.source_symbol_id)::int AS count
       FROM symbol_references sr
       JOIN symbols s ON sr.source_symbol_id = s.id
       JOIN files f ON s.file_id = f.id
       WHERE f.repo_id = $1 AND sr.reference_kind = 'trait_use'`,
      [repoId]
    );

    const { rows: adoptionRows } = await this.pool.query(
      `SELECT
         split_part(f.path, '/', 1) ||
           CASE WHEN position('/' in f.path) > 0
                THEN '/' || split_part(f.path, '/', 2)
                ELSE '' END AS module,
         COUNT(DISTINCT s.id)::int AS total,
         COUNT(DISTINCT sr.source_symbol_id)::int AS with_interface
       FROM symbols s
       JOIN files f ON s.file_id = f.id
       LEFT JOIN symbol_references sr ON sr.source_symbol_id = s.id AND sr.reference_kind = 'implementation'
       WHERE f.repo_id = $1 AND s.kind = 'class' AND s.parent_symbol_id IS NULL
       GROUP BY module
       ORDER BY total DESC`,
      [repoId]
    );

    const adoptionMap = new Map<string, { total: number; withInterface: number }>();
    for (const row of adoptionRows) {
      adoptionMap.set(row.module as string, {
        total: row.total as number,
        withInterface: row.with_interface as number,
      });
    }

    const { rows: classNameRows } = await this.pool.query(
      `SELECT s.name FROM symbols s JOIN files f ON s.file_id = f.id
       WHERE f.repo_id = $1 AND s.kind = 'class' AND s.parent_symbol_id IS NULL
       LIMIT 200`,
      [repoId]
    );

    const { rows: methodNameRows } = await this.pool.query(
      `SELECT s.name FROM symbols s JOIN files f ON s.file_id = f.id
       WHERE f.repo_id = $1 AND s.kind = 'method'
         AND s.name NOT LIKE E'\\_\\_%'
       LIMIT 200`,
      [repoId]
    );

    return {
      totalClasses: (countMap.class || 0) as number,
      totalInterfaces: (countMap.interface || 0) as number,
      totalTraits: (countMap.trait || 0) as number,
      totalEnums: (countMap.enum || 0) as number,
      classesWithInterface: implCount[0].count as number,
      classesWithInheritance: inheritCount[0].count as number,
      classesWithTraits: traitCount[0].count as number,
      interfaceAdoptionByModule: adoptionMap,
      classNames: classNameRows.map(r => r.name as string),
      methodNames: methodNameRows.map(r => r.name as string),
    };
  }
}
