import type pg from 'pg';
import { resolve } from 'path';
import { mkdirSync, writeFileSync } from 'fs';
import { RepoRepository } from '../db/repositories/repo-repository.js';
import { GenerateError } from '../errors.js';

const HEADER = '<!-- Generated by Cartograph. Do not edit manually. -->\n\n';

export interface GenerateOptions {
  outputDir?: string;
}

export class GeneratePipeline {
  private repoRepo: RepoRepository;

  constructor(private pool: pg.Pool) {
    this.repoRepo = new RepoRepository(pool);
  }

  async run(repoPath: string, opts: GenerateOptions = {}): Promise<void> {
    const absPath = resolve(repoPath);
    const outputDir = opts.outputDir || `${absPath}/.cartograph`;

    // 1. Find the repo in the DB
    const repo = await this.repoRepo.findByPath(absPath);
    if (!repo) {
      throw new GenerateError(
        `Repository not indexed: ${absPath}. Run \`cartograph index <path>\` first.`
      );
    }

    // 2. Check for empty index
    const { rows: fileCount } = await this.pool.query(
      'SELECT COUNT(*)::int AS count FROM files WHERE repo_id = $1',
      [repo.id]
    );
    if ((fileCount[0].count as number) === 0) {
      throw new GenerateError(
        `No indexed data found for ${absPath}. Run \`cartograph index <path>\` first.`
      );
    }

    // 3. Generate files
    mkdirSync(outputDir, { recursive: true });

    // Placeholder — will be replaced as generators are built
    writeFileSync(`${outputDir}/CLAUDE.md`, HEADER + '# Project Overview\n\n_Coming soon_\n');
    writeFileSync(`${outputDir}/modules.md`, HEADER + '# Modules\n\n_Coming soon_\n');
    writeFileSync(`${outputDir}/dependencies.md`, HEADER + '# Dependencies\n\n_Coming soon_\n');
    writeFileSync(`${outputDir}/conventions.md`, HEADER + '# Conventions\n\n_Coming soon_\n');

    // 4. Print summary
    console.log('\n✅ Generated .cartograph/CLAUDE.md + 3 topic files');
    console.log('   Add this to your root CLAUDE.md:');
    console.log('   Also read: .cartograph/CLAUDE.md\n');
  }
}
