import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import Database from 'better-sqlite3';
import { openDatabase } from '../../src/db/connection.js';
import { runMigrations } from '../../src/db/migrate.js';
import { IndexPipeline } from '../../src/indexer/pipeline.js';
import { GeneratePipeline } from '../../src/output/generate-pipeline.js';
import { join } from 'path';
import { readFileSync, existsSync, rmSync } from 'fs';
import type { CartographConfig } from '../../src/types.js';

const FIXTURES = join(import.meta.dirname, '..', 'fixtures', 'laravel-sample');
const OUTPUT_DIR = join(import.meta.dirname, '..', 'fixtures', 'laravel-sample', '.cartograph');

function testConfig(): CartographConfig {
  return {
    languages: ['php'],
    exclude: ['vendor/'],
    database: { path: ':memory:' },
  };
}

describe('Generate Pipeline (Integration)', () => {
  let db: Database.Database;

  beforeAll(() => {
    db = openDatabase({ path: ':memory:' });
    runMigrations(db);
  });

  afterAll(() => {
    if (existsSync(OUTPUT_DIR)) {
      rmSync(OUTPUT_DIR, { recursive: true });
    }
    db.close();
  });

  beforeEach(() => {
    db.exec('DELETE FROM symbol_references');
    db.exec('DELETE FROM symbols');
    db.exec('DELETE FROM files');
    db.exec('DELETE FROM repos');
    if (existsSync(OUTPUT_DIR)) {
      rmSync(OUTPUT_DIR, { recursive: true });
    }
  });

  it('generates all four files', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(db);
    genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    expect(existsSync(join(OUTPUT_DIR, 'CLAUDE.md'))).toBe(true);
    expect(existsSync(join(OUTPUT_DIR, 'modules.md'))).toBe(true);
    expect(existsSync(join(OUTPUT_DIR, 'dependencies.md'))).toBe(true);
    expect(existsSync(join(OUTPUT_DIR, 'conventions.md'))).toBe(true);
  });

  it('files have the generated header', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(db);
    genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    const header = '<!-- Generated by Cartograph. Do not edit manually. -->';
    for (const file of ['CLAUDE.md', 'modules.md', 'dependencies.md', 'conventions.md']) {
      const content = readFileSync(join(OUTPUT_DIR, file), 'utf-8');
      expect(content.startsWith(header)).toBe(true);
    }
  });

  it('root CLAUDE.md contains expected sections', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(db);
    genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    const content = readFileSync(join(OUTPUT_DIR, 'CLAUDE.md'), 'utf-8');
    expect(content).toContain('# Project Overview');
    expect(content).toContain('## Architecture');
    expect(content).toContain('## Directory Map');
    expect(content).toContain('[Modules](modules.md)');
  });

  it('modules.md lists fixture classes', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(db);
    genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    const content = readFileSync(join(OUTPUT_DIR, 'modules.md'), 'utf-8');
    // Fixture modules have 1 file each, so they render in Standalone Files section
    expect(content).toContain('app/Services');
    expect(content).toContain('app/Http');
  });

  it('dependencies.md shows directed references', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(db);
    genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    const content = readFileSync(join(OUTPUT_DIR, 'dependencies.md'), 'utf-8');
    expect(content).toContain('\u2192');
    expect(content).toContain('refs)');
  });

  it('is idempotent \u2014 re-generating produces same content', () => {
    const indexPipeline = new IndexPipeline(db);
    indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(db);
    genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });
    const first = readFileSync(join(OUTPUT_DIR, 'CLAUDE.md'), 'utf-8');

    genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });
    const second = readFileSync(join(OUTPUT_DIR, 'CLAUDE.md'), 'utf-8');

    expect(first).toBe(second);
  });
});
