import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import pg from 'pg';
import { IndexPipeline } from '../../src/indexer/pipeline.js';
import { GeneratePipeline } from '../../src/output/generate-pipeline.js';
import { join } from 'path';
import { readFileSync, existsSync, rmSync } from 'fs';
import type { CartographConfig } from '../../src/types.js';

const TEST_DB = {
  host: 'localhost',
  port: 5435,
  database: 'cartograph_test',
  user: 'cartograph',
  password: 'localdev',
};

const FIXTURES = join(import.meta.dirname, '..', 'fixtures', 'laravel-sample');
const OUTPUT_DIR = join(import.meta.dirname, '..', 'fixtures', 'laravel-sample', '.cartograph');

function testConfig(): CartographConfig {
  return {
    languages: ['php'],
    exclude: ['vendor/'],
    database: {
      host: TEST_DB.host,
      port: TEST_DB.port,
      name: TEST_DB.database,
      user: TEST_DB.user,
      password: TEST_DB.password,
    },
  };
}

describe('Generate Pipeline (Integration)', () => {
  let pool: pg.Pool;

  beforeAll(() => {
    pool = new pg.Pool(TEST_DB);
  });

  afterAll(async () => {
    if (existsSync(OUTPUT_DIR)) {
      rmSync(OUTPUT_DIR, { recursive: true });
    }
    await pool.end();
  });

  beforeEach(async () => {
    await pool.query('DELETE FROM symbol_references');
    await pool.query('DELETE FROM symbols');
    await pool.query('DELETE FROM files');
    await pool.query('DELETE FROM repos');
    if (existsSync(OUTPUT_DIR)) {
      rmSync(OUTPUT_DIR, { recursive: true });
    }
  });

  it('generates all four files', async () => {
    const indexPipeline = new IndexPipeline(pool);
    await indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(pool);
    await genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    expect(existsSync(join(OUTPUT_DIR, 'CLAUDE.md'))).toBe(true);
    expect(existsSync(join(OUTPUT_DIR, 'modules.md'))).toBe(true);
    expect(existsSync(join(OUTPUT_DIR, 'dependencies.md'))).toBe(true);
    expect(existsSync(join(OUTPUT_DIR, 'conventions.md'))).toBe(true);
  });

  it('files have the generated header', async () => {
    const indexPipeline = new IndexPipeline(pool);
    await indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(pool);
    await genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    const header = '<!-- Generated by Cartograph. Do not edit manually. -->';
    for (const file of ['CLAUDE.md', 'modules.md', 'dependencies.md', 'conventions.md']) {
      const content = readFileSync(join(OUTPUT_DIR, file), 'utf-8');
      expect(content.startsWith(header)).toBe(true);
    }
  });

  it('root CLAUDE.md contains expected sections', async () => {
    const indexPipeline = new IndexPipeline(pool);
    await indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(pool);
    await genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    const content = readFileSync(join(OUTPUT_DIR, 'CLAUDE.md'), 'utf-8');
    expect(content).toContain('# Project Overview');
    expect(content).toContain('## Architecture');
    expect(content).toContain('## Directory Map');
    expect(content).toContain('[Modules](modules.md)');
  });

  it('modules.md lists fixture classes', async () => {
    const indexPipeline = new IndexPipeline(pool);
    await indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(pool);
    await genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    const content = readFileSync(join(OUTPUT_DIR, 'modules.md'), 'utf-8');
    // Fixture modules have 1 file each, so they render in Standalone Files section
    expect(content).toContain('app/Services');
    expect(content).toContain('app/Http');
  });

  it('dependencies.md shows directed references', async () => {
    const indexPipeline = new IndexPipeline(pool);
    await indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(pool);
    await genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });

    const content = readFileSync(join(OUTPUT_DIR, 'dependencies.md'), 'utf-8');
    expect(content).toContain('→');
    expect(content).toContain('refs)');
  });

  it('is idempotent — re-generating produces same content', async () => {
    const indexPipeline = new IndexPipeline(pool);
    await indexPipeline.run(FIXTURES, testConfig());

    const genPipeline = new GeneratePipeline(pool);
    await genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });
    const first = readFileSync(join(OUTPUT_DIR, 'CLAUDE.md'), 'utf-8');

    await genPipeline.run(FIXTURES, { outputDir: OUTPUT_DIR });
    const second = readFileSync(join(OUTPUT_DIR, 'CLAUDE.md'), 'utf-8');

    expect(first).toBe(second);
  });
});
